apiVersion: skaffold/v2beta12
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: cheatcodesam/minechain-web
      context: web
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.tsx"
            dest: .
    - image: cheatcodesam/minechain-backend
      context: backend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.tsx"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./k8s/*
