import Provider from './components/Provider'
import './global.css'

export const metadata = {
  title: 'Welcome to frontend-app',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <body>{children}</body>
      </Provider>
    </html>
  )
}
