name: MinechainMain
version: 1.0.0
main: com.minechain.minechain.App
description: The main server plugin for Minechain
author: Carson Weeks
website: https://github.com/CheatCodeSam/Minechain
api-version: 1.19