FROM node:17.4.0-alpine3.15 as build

WORKDIR /usr/app

COPY package*.json ./
RUN npm install
ADD . .
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/app/dist /usr/share/nginx/html